import React, { useState, useEffect, useRef } from 'react';
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithCustomToken, signInAnonymously, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, doc, setDoc } from 'firebase/firestore';
import { PlusCircle, Loader, CheckCircle, XCircle, Users, Key } from 'lucide-react';

// --- Global Variable Access ---
const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';
const firebaseConfig = JSON.parse(typeof __firebase_config !== 'undefined' ? __firebase_config : '{}');
const initialAuthToken = typeof __initial_auth_token !== 'undefined' ? __initial_auth_token : null;

// The main application component
const App = () => {
  const [storeName, setStoreName] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('Food');
  const [deliveryTime, setDeliveryTime] = useState('30-45');
  const [rating, setRating] = useState('4.5');
  
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [message, setMessage] = useState(null); // { type: 'success'|'error', text: '...' }
  const [userId, setUserId] = useState(null);
  const [authReady, setAuthReady] = useState(false);

  const firebaseRef = useRef({ db: null, auth: null });

  // 1. Initialize Firebase and Authenticate
  useEffect(() => {
    let unsubscribeAuth = () => {};

    const initFirebase = async () => {
      try {
        if (Object.keys(firebaseConfig).length === 0) {
          throw new Error("Firebase configuration is missing.");
        }

        const app = initializeApp(firebaseConfig);
        const auth = getAuth(app);
        const db = getFirestore(app);
        firebaseRef.current = { db, auth };

        // Set up Auth State Listener
        unsubscribeAuth = onAuthStateChanged(auth, (user) => {
          if (user) {
            setUserId(user.uid);
          } else {
            setUserId(null);
          }
          setAuthReady(true);
        });

        // Sign in using provided token or anonymously
        if (initialAuthToken) {
          await signInWithCustomToken(auth, initialAuthToken);
        } else {
          await signInAnonymously(auth);
        }

      } catch (e) {
        console.error("Firebase Initialization Error:", e);
        setMessage({ type: 'error', text: `Initialization Failed: ${e.message}` });
        setAuthReady(true); 
      }
    };

    initFirebase();

    return () => unsubscribeAuth();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!authReady || !firebaseRef.current.db) {
      setMessage({ type: 'error', text: 'Application is not fully initialized. Please wait.' });
      return;
    }
    if (!userId) {
       setMessage({ type: 'error', text: 'User is not authenticated. Cannot submit store.' });
       return;
    }
    
    // Clear previous messages
    setMessage(null);
    setIsSubmitting(true);

    const newStoreData = {
      name: storeName,
      description: description,
      category: category,
      deliveryTime: deliveryTime,
      rating: parseFloat(rating),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    try {
      // The document ID is generated by the current timestamp for simplicity
      const docId = `store_${Date.now()}`;
      const collectionPath = `artifacts/${appId}/public/data/stores`;
      const storeDocRef = doc(firebaseRef.current.db, collectionPath, docId);

      await setDoc(storeDocRef, newStoreData);

      setMessage({ type: 'success', text: `Store "${storeName}" created successfully! It is now visible in the Client App.` });
      // Reset form
      setStoreName('');
      setDescription('');
      setIsSubmitting(false);

    } catch (e) {
      console.error("Firestore Write Error:", e);
      // This is where the security rule denial error will be caught if the user lacks the 'admin_user' role
      setMessage({ 
        type: 'error', 
        text: `Write Failed. Ensure you have the 'admin_user' role in Firestore. Error: ${e.message}` 
      });
      setIsSubmitting(false);
    }
  };

  const categories = ['Food', 'Grocery', 'Beverage', 'Pharmacy', 'Other'];

  return (
    <div className="min-h-screen bg-gray-100 font-sans p-4">
      <header className="bg-white shadow-lg rounded-xl p-5 mb-6 max-w-4xl mx-auto">
        <div className="flex justify-between items-center">
          <h1 className="text-3xl font-extrabold text-indigo-700 flex items-center">
            <Users className="w-6 h-6 mr-3" /> Admin Dashboard
          </h1>
          <div className="text-sm text-gray-600">
            <p className="font-semibold">App ID: {appId}</p>
            <p>User ID: {userId || 'N/A'}</p>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto">
        <div className="mb-6 p-4 rounded-lg shadow-md bg-yellow-50 border border-yellow-300">
          <div className="flex items-center text-yellow-800">
            <Key className="w-5 h-5 mr-2" />
            <p className="text-sm font-medium">
              **SECURITY NOTE:** Store creation requires the 'admin\_user' role in Firestore. If the write fails, you must ensure your User ID ({userId || '...'}) has the required role document created under its private space: `artifacts/{appId}/users/{userId}/roles/admin_user`.
            </p>
          </div>
        </div>
        
        <div className="bg-white p-8 rounded-xl shadow-2xl">
          <h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
            <PlusCircle className="w-5 h-5 mr-2 text-green-600" /> Create New Store Entry
          </h2>

          {/* Submission Message */}
          {message && (
            <div className={`p-4 rounded-lg mb-6 flex items-center ${
              message.type === 'success' 
                ? 'bg-green-100 text-green-800 border border-green-300' 
                : 'bg-red-100 text-red-800 border border-red-300'
            }`}>
              {message.type === 'success' ? <CheckCircle className="w-5 h-5 mr-3" /> : <XCircle className="w-5 h-5 mr-3" />}
              <p className="font-medium">{message.text}</p>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label htmlFor="storeName" className="block text-sm font-medium text-gray-700 mb-1">Store Name</label>
              <input
                id="storeName"
                type="text"
                value={storeName}
                onChange={(e) => setStoreName(e.target.value)}
                required
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 transition duration-150"
                placeholder="e.g., Tasty Bites Restaurant"
              />
            </div>

            <div>
              <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-1">Description</label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                required
                rows="3"
                className="w-full p-3 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 transition duration-150"
                placeholder="A short description of the store or its specialty."
              ></textarea>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
              <div>
                <label htmlFor="category" className="block text-sm font-medium text-gray-700 mb-1">Category</label>
                <select
                  id="category"
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 transition duration-150 bg-white"
                >
                  {categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                </select>
              </div>

              <div>
                <label htmlFor="rating" className="block text-sm font-medium text-gray-700 mb-1">Rating (e.g., 4.5)</label>
                <input
                  id="rating"
                  type="number"
                  step="0.1"
                  min="0"
                  max="5"
                  value={rating}
                  onChange={(e) => setRating(e.target.value)}
                  required
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 transition duration-150"
                />
              </div>
              
              <div>
                <label htmlFor="deliveryTime" className="block text-sm font-medium text-gray-700 mb-1">Delivery Time (min)</label>
                <input
                  id="deliveryTime"
                  type="text"
                  value={deliveryTime}
                  onChange={(e) => setDeliveryTime(e.target.value)}
                  required
                  className="w-full p-3 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 transition duration-150"
                  placeholder="e.g., 30-45"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={isSubmitting || !authReady || !userId}
              className={`w-full flex justify-center items-center py-3 px-4 border border-transparent rounded-lg shadow-xl text-lg font-semibold text-white transition duration-200 ${
                isSubmitting || !userId ? 'bg-indigo-400 cursor-not-allowed' : 'bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-4 focus:ring-indigo-500 focus:ring-opacity-50'
              }`}
            >
              {isSubmitting ? (
                <>
                  <Loader className="w-5 h-5 mr-3 animate-spin" /> Submitting...
                </>
              ) : (
                <>
                  <PlusCircle className="w-5 h-5 mr-2" /> Add Store to Catalog
                </>
              )}
            </button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default App;
